### ISSUE TITLE
克隆下来报错

### ISSUE THREAD

**Issue by winnxiegang** [albert-lii/Fly-Android#2]
> Task :app:kaptDebugKotlin FAILED
D:\Code\android\githubSam\Fly-Android\app\build\generated\source\kapt\debug\com\fly\example\DataBinderMapperImpl.java:12: 错误: 找不到符号
import com.fly.example.databinding.ActivityLivebusFirstBindingImpl;
                                  ^
  符号:   类 ActivityLivebusFirstBindingImpl
  位置: 程序包 com.fly.example.databindingD:\Code\android\githubSam\Fly-Android\app\build\generated\source\kapt\debug\com\fly\example\DataBinderMapperImpl.java:13: 错误: 找不到符号
import com.fly.example.databinding.ActivityLivebusSecondBindingImpl;
                                  ^
  符号:   类 ActivityLivebusSecondBindingImpl
  位置: 程序包 com.fly.example.databinding
FAILURE: Build failed with an exception.

**Comment by albert-lii** [comment]
已修复
